#配置数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false"
    username: root
    password:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

#配置Mybatis
mybatis:
  config-location: classpath:mybatis.xml
  mapper-locations: classpath:mapper/*.xml